### PR TITLE
[RFC] DDF and pktio code structure cleanup

### PR DESCRIPTION
**Pull request by heyi-arm**
I'd like to do below cleanup and structure re-organization, please see if this looks good to you:

1 cleanup odpdrv copies of align, atomic, barrier, byteorder,
  compiler,hints,shm,spinlock,std_types,sync
    -- no need to duplicate these for driver development, use the ODP APIs
2, move driver framework headers and sources into framework/driver/
  -- assume ODP driver developers will work with ODP repo as their environment
3, move pktio/common, sysfs, ethtool, ring and linked list into framework/utils
  -- these are general utilities used by all aspects of ODP implementations
4, rename platform/linux-generic/_modules.c to module_loader.c

Signed-off-by: Yi He <yi.he@linaro.org>

### CODE REVIEW

**Review by joseppc — COMMENTED** [review]
Breaks the build. Also we'd need to keep odpdrv_shm* or remove _ishmphy all together (and modify pci_drv.c to use odp_shm_* instead, I could do that).

I suggest deleting stuff, and moving code to the framework/ directory in different commits which don't break the build, although I suppose the main goal of the patch is for now to start a discussion about restructuring and refactoring the code base.

**Comment by heyi-live** [comment]
Hey, it is nice to talk in Github PR, nice reading than email 👍 also has emoji!!

Yes, this is only a RFC to trigger the discussion, and it breaks the build. For the memory part Honnappa said he will take care and there should be more to cleanup _ishm_*.

**Comment by joseppc** [comment]
I removed the dependency on odpdrv_shm in drv_pci.c, and maybe an idea for removing _ishmphy.c could be doing something similar to what Matias Elo did in odp-dpdk, which replaced it by dpdk's memzones (if applicable)

**Comment by heyi-arm** [comment]
yes, Josep, agree Matias's patch seems the right direction, what driver needs for memory is rte_malloc/memzone for descriptors/rings and packet pool for packet buffers.

this patch is only for expressing the idea and reached some agreements:

- moving driver framework sources and headers to framework/driver
  -- I mean those DPDK pci bus driver and uio/vfio operations
- cleanup odpdrv copies of align, atomic, barrier, byteorder, compiler,hints,shm,spinlock,std_types,sync

for the ishm_* cleanup and code refinement Honnappa said he will look into it

**Pull request closed without merging**
